### ISSUE TITLE
Problem with Google Music API?

### ISSUE THREAD

**Issue by MikeKleinSYNA** [maxkirchoff/google-music-dupe-killer#10]
I haven't seen anyone else make this comment so I will. I've used this script and another like it with the latest version of googlemusicapi and both yield this result:

...
    logged_in = api.login('someone@gmail.com', 'my_password')
TypeError: login() takes exactly 4 arguments (3 given)

Of course the name and password shown here are not mine. Is it possible the API has changed? Or perhaps I've installed the wrong one?

**Comment by JagerBomb** [comment]
That doesn't happen to me, what api are you using? I'm using Mobileclient:

from gmusicapi import Mobileclient
api = Mobileclient()
username = '<my_email>@gmail.com'  
pwd = getpass.getpass("Input password for account [%s]: " % username)
logged_in = api.login(username, pwd)

**Comment by MikeKleinSYNA** [comment]
Update: I couldn't find the source of the problem but it happened with 3 different clients. So, I uninstalled and reinstalled the API and now it works.
