### ISSUE TITLE
Code 500 - Internal error

### ISSUE THREAD

**Issue by jorti** [maxkirchoff/google-music-dupe-killer#13]
Hi, I'm unable to delete my duplicates. It shows me a list of +6000 songs to be deleted, but it fails with this error.

Is this something we can fix client side?

[huge list of uuids skipped]
{"delete": "ddb363d0-c7f6-3677-a2bd-5401efdc3d7c"}, {"delete": "9966ace5-44b6-337f-865b-e5016c16ce05"}, {"delete": "c5b56671-68dc-3aba-869e-001a6c70517a"}, {"delete": "73567e3f-3c1e-3da1-b602-bb66169d1506"}]}', u'method': u'POST', u'params': {u'tier': u'fr', u'alt': u'json', u'hl': u'en_US'}})
(response was: u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "internalError",\n    "message": "Internal Error"\n   }\n  ],\n  "code": 500,\n  "message": "Internal Error"\n }\n}\n')

**Comment by jorti** [comment]
Deleting them one by one works. I've made a for loop:

```
            for s in duplicate_track_ids:
                deleted_track_ids = api.delete_songs(s)
```

**Comment by acidrefluxdisease** [comment]
hi jorti,

could you tell me where to add your lines in the original script?

**Comment by jorti** [comment]
I've created PR #14
