### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by jbresle** [maxkirchoff/google-music-dupe-killer#21]
Hi - trying to run - logged in successfully, but got the following on Windows 10:

C:\Python33\google-music-dupe-killer-master>kill_dupes.py
Successfully logged in. Beginning duplicate detection process.
Traceback (most recent call last):
  File "C:\Python33\google-music-dupe-killer-master\kill_dupes.py", line 107, in <module>
    album_track_duplicate_map = map_track_duplication(all_tracks)
  File "C:\Python33\google-music-dupe-killer-master\kill_dupes.py", line 12, in map_track_duplication
    trackNumberNorm = track['trackNumber']
KeyError: 'trackNumber'

C:\Python33\google-music-dupe-killer-master>

Any ideas?

Thanks,

Jon

**Comment by eboye** [comment]
Hmm, I have similiar issue:

```
Successfully logged in. Beginning duplicate detection process.
Traceback (most recent call last):
  File "./kill_dupes", line 107, in <module>
    album_track_duplicate_map = map_track_duplication(all_tracks)
  File "./kill_dupes", line 12, in map_track_duplication
    trackNumberNorm = track['trackNumber']
KeyError: 'trackNumber'
```

I suppose API is updated and the code is not adapted :|

**Comment by jbresle** [comment]
I have made modifications to the code to skip tracks which have missing information and it worked for me.   I have attached my modified version of the code - I hope it works for you as well eboye.


[kill_dupes.txt](https://github.com/maxkirchoff/google-music-dupe-killer/files/447249/kill_dupes.txt)

**Comment by eboye** [comment]
Thanks @jbresle :) I'll try it right away

**Comment by mrbinky3000** [comment]
Same issue.  @jbresle you should make a pull request.

**Comment by maxkirchoff** [comment]
This is fixed.
