### ISSUE TITLE
input() not working on Windows via git bash

### ISSUE THREAD

**Issue by TheHanna** [maxkirchoff/google-music-dupe-killer#24]
Thanks for the library.

I ended up having to change line 84 from using `input()` to `raw_input()` to get rid of the following error:

```
Traceback (most recent call last):
  File "kill_dupes.py", line 113, in <module>
    if query_yes_no("Found " + str(len(duplicate_track_ids)) + " duplicate tracks. Delete duplicates?", "no"):
  File "kill_dupes.py", line 84, in query_yes_no
    choice = input().lower()
  File "<string>", line 1, in <module>
NameError: name 'yes' is not defined
```

`input()` tries to evaluate the input; `raw_input()` simply takes the string, which seems to be what is needed here.

**Comment by maxkirchoff** [comment]
I merged the fix for this now.

**Comment by livejamie** [comment]
This fixed a problem I was having, thank you.
