### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by Kolano** [maxkirchoff/google-music-dupe-killer#3]
The script bombs out every time it hits non-ansi unicode characters in my track titles.

```
Traceback (most recent call last):
  File "C:\Users\kmk\Desktop\kill_dupes.py", line 56, in <module>
    duplicate_tracks = get_duplicate_tracks(all_tracks_by_album, album_track_duplicate_map)
  File "C:\Users\kmk\Desktop\kill_dupes.py", line 35, in get_duplicate_tracks
    print "Queueing for removal: " + track['titleNorm'] + " from album " + track['albumNorm'] + " by " + track['artist']

  File "C:\Program Files (UAC Off)\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-25: character maps to <undefined>
```

**Comment by RollingStar** [comment]
I don't know why this is, but it works on Unicode files when I run IDLE. This is far preferable to it crashing outright. I think it successfully removes the dupes, but at a minimum it's skipping over the Unicode-based dupes.

This is on Win10 x64 and Python 2.7.10.

>Queueing for removal: 'ゲームセレクト' from album 'リズム天国全曲集' by 'つんく♂  
>Queueing for removal: 'ハイレベル' from album 'リズム天国全曲集' by '米 政美

    IDLE -> file -> open -> kill_dupes.py
    IDLE -> run -> run module

**Comment by maseric** [comment]
Solution that worked for me (found here : http://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined) : 

add these lines at the begining of file :
# -*- coding: utf-8 -*-
import codecs
sys.stdout = codecs.getwriter("iso-8859-1")(sys.stdout, 'xmlcharrefreplace

**Comment by edthepenguin** [comment]
I'm not very python-savvy, but this seemed to work for me.. Replace line 41:
`print "Queueing for removal: '" + track['title'] + "' from album '" + track['album'] + "' by '"  + track['artist']`

with:
`queuemsg = "Queueing for removal: '" + track['title'] + "' from album '" + track['album'] + "' by '"  + track['artist']
                                print queuemsg.encode('ascii', 'ignore') `
