### ISSUE TITLE
Error when confirming deletion of dupes

### ISSUE THREAD

**Issue by nbanbury** [maxkirchoff/google-music-dupe-killer#30]
When I get to this part of the process: "Found xx duplicate tracks. Delete duplicates? [y/N]"

Entering "y" and pressing enter gives me this error:
"Traceback (most recent call last):
  File "C:\Python27\kill_dupes.py", line 122, in <module>
    if query_yes_no("Found " + str(len(duplicate_track_ids)) + " duplicate tracks. Delete duplicates?"):
  File "C:\Python27\kill_dupes.py", line 94, in query_yes_no
    choice = input().lower()
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined"

Can someone advise/help?

Thanks

**Comment by giwrgos88** [comment]
I have the same issue

**Comment by ktully** [comment]
Have you tried with python 3 per the README? 

Your path suggests you're using python 2.7 on windows, which is not supported.

**Comment by giwrgos88** [comment]
@ktully 3.5.3 is fine?

**Comment by nbanbury** [comment]
Apologies I didn't try with Python 3. Will do so and report back.

**Comment by ktully** [comment]
@giwrgos88 I've use it with python 3.6.0 on windows, but I'd expect earlier 3 variants should work too.

**Comment by giwrgos88** [comment]
still the same error on mac

**Comment by ktully** [comment]
@giwrgos88 Then you're still running it undre python 2. The error is indicative of the python 2 behaviour where input() does an eval(). https://docs.python.org/2/library/functions.html#input

Quick fix for you is to change input() to raw_input() in your local copy of the script.

Meanwhile I've opened a pull request to auto-detect the python version and hopefully avoid this class of issues in future.

**Comment by giwrgos88** [comment]
you are right i switched to latest python. i saw your commits and replaced the input with raw_input in order to make it work. thanks

**Comment by nbanbury** [comment]
Fantastic service, thanks for the fix, I've sorted it all now.
