### ISSUE TITLE
gmusicapi not found on osx

### ISSUE THREAD

**Issue by krazyjakee** [maxkirchoff/google-music-dupe-killer#4]
```
from gmusicapi import Webclient
ImportError: No module named gmusicapi
```

Getting that when I try to run the script. I've installed gmusicapi through pip as described in the readme. Is there some step the readme is missing?

**Comment by david-cako** [comment]
Old thread, but make sure you're using "pip3 install gmusicapi" if you have python2 and python3 running alongside one another.
