### ISSUE TITLE
Script still working?

### ISSUE THREAD

**Issue by Maundler** [maxkirchoff/google-music-dupe-killer#8]
Hi Max,

I was wondering if you can help me out with this script - if it still works that is.

I am running Windows, and I already installed python and already installed gmusicapi and already opened up and edited mobileclient.py and musicmanager.py and included my email and password - I imported from gmusicapi import Mobileclient - and then ran the program through CMD in windows, and it doesn't send any errors, but it does nothing, just gets a new command line as if nothing happened. BTW - I also installed and pointed to the directory for the recent stats binaries to avconv.exe - I think I have done everything yet nothing seems to work.

Can you help me out figuring what I'm doing wrong?

Thanks!
JC

**Comment by JagerBomb** [comment]
API still works, I wrote a little script to take my music library and generate an XML file with a list of all my albums (artist, year, cover, etc...) and so far it works. I had to modify it a little bit to accept unicode characters.

I don't know what you mean by 'running the program'. This is an API, it provides some methods to access your Google Music library. 

To verify it works you can try running in python:
from gmusicapi import Mobileclient
api = Mobileclient()
username = [your_email_address]
pwd = [your_google_password]
api.login(username, pwd)
api.get_all_songs()

**Comment by dbkaplun** [comment]
@Maundler I just ran the script successfully, so it definitely works. If you have 2-Factor Auth enabled on your account, you may need to set up an app password: https://support.google.com/accounts/answer/185833
